# Generated by Django 4.1.3 on 2023-01-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0026_alter_artwork_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(),
        ),
    ]
