# Generated by Django 4.1.3 on 2023-02-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0026_alter_artwork_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="year_created",
        ),
    ]
