# Generated by Django 4.1.3 on 2023-02-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0027_remove_artwork_year_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="What_might_work",
            new_name="comments",
        ),
        migrations.RemoveField(
            model_name="review",
            name="Sum_it_up",
        ),
        migrations.RemoveField(
            model_name="review",
            name="What_needs_work",
        ),
        migrations.RemoveField(
            model_name="review",
            name="What_works",
        ),
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.AddField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[("up", "Up Vote"), ("down", "Down Vote")],
                default="How did they do?",
                max_length=200,
            ),
        ),
    ]
