# Generated by Django 4.1.3 on 2023-02-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0028_rename_what_might_work_review_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[("up", "Up Vote"), ("down", "Down Vote")],
                default="Responses:",
                max_length=200,
            ),
        ),
    ]
