# Generated by Django 4.1.3 on 2023-02-08 20:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("panelists", "0011_message"),
        ("artworks", "0029_alter_review_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "stars",
                    models.CharField(
                        choices=[
                            ("&#11088; ", "One"),
                            ("&#11088; &#11088; ", "Two"),
                            ("&#11088; &#11088; &#11088; ", "Three"),
                            ("&#11088; &#11088; &#11088; &#11088; ", "Four"),
                            ("&#11088; &#11088; &#11088; &#11088; &#11088; ", "Five"),
                        ],
                        default="&#11088; &#11088; &#11088; ",
                        max_length=50,
                    ),
                ),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artworks.artwork",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="panelists.profile",
                    ),
                ),
            ],
        ),
    ]
