# Generated by Django 4.1.3 on 2023-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0030_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
