# Generated by Django 4.1.3 on 2023-02-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0031_feedback_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artwork",
            options={
                "ordering": [
                    "-star_ratio",
                    "-star_total",
                    "-vote_ratio",
                    "-vote_total",
                    "title",
                ]
            },
        ),
        migrations.AddField(
            model_name="artwork",
            name="star_ratio",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="star_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.CharField(
                choices=[
                    ("&#11088; ", "One"),
                    ("&#11088; &#11088; ", "Two"),
                    ("&#11088; &#11088; &#11088; ", "Three"),
                    ("&#11088; &#11088; &#11088; &#11088; ", "Four"),
                    ("&#11088; &#11088; &#11088; &#11088; &#11088; ", "Five"),
                ],
                default="&#11088; &#11088; &#11088; ",
                max_length=50,
            ),
        ),
    ]
